version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: RedisWorker/Dockerfile
    container_name: switchly-worker
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=switchly;Username=postgres;Password=postgrespw;Ssl Mode=Disable
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Pass: guest
      Cache__Redis__Connection: redis:6379,abortConnect=false
      Switchly__OrgClientKey: dev-org
    depends_on:
      - postgres
      - rabbitmq
      - redis
  api:
    build:
      context: .                # repo kökü
      dockerfile: Dockerfile    # kökteki Dockerfile
    container_name: switchly-api
    ports:
      - "8090:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=switchly;Username=postgres;Password=postgrespw;Ssl Mode=Disable
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Pass: guest
      Cache__Redis__Connection: redis:6379,abortConnect=false
      Switchly__OrgClientKey: dev-org
    depends_on:
      - postgres
      - rabbitmq
      - redis
  postgres:
    image: postgres:latest
    container_name: switchly-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: switchly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # AMQP (MassTransit gibi servisler için)
      - "15672:15672"   # Web UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  rabbitmq:
  redis:
  postgres_data:
    driver: local

